name: Daily Readme Update

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:
jobs:
  interactive-readme-tools:
    name: Interactive README Update
    runs-on: ubuntu-latest
    steps:
      # Step 1: Update Lines of Code Stats
      - name: Update the Lines of Code written so far
        uses: anmol098/waka-readme-stats@master
        with:
          SECTION_NAME: lines-of-code
          COMMIT_MESSAGE: "doc(loc): Update Lines of Code section in README"
          SHOW_UPDATED_DATE: False
          SHOW_LINES_OF_CODE: True
          SHOW_TOTAL_CODE_TIME: False
          SHOW_PROFILE_VIEWS: False
          SHOW_COMMIT: False
          SHOW_DAYS_OF_WEEK: False
          SHOW_LANGUAGE: False
          SHOW_OS: False
          SHOW_PROJECTS: False
          SHOW_TIMEZONE: False
          SHOW_EDITORS: False
          SHOW_LANGUAGE_PER_REPO: False
          SHOW_SHORT_INFO: False
          IGNORED_REPOS: "mrasadatik"
          SHOW_LOC_CHART: False
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      # Step 1: Update Code Time
      - name: Update the Code Time
        uses: anmol098/waka-readme-stats@master
        with:
          SECTION_NAME: coding-time
          COMMIT_MESSAGE: "doc(ct-stats): Update Code Time section in README"
          SHOW_UPDATED_DATE: False
          SHOW_LINES_OF_CODE: False
          SHOW_TOTAL_CODE_TIME: True
          SHOW_PROFILE_VIEWS: False
          SHOW_COMMIT: False
          SHOW_DAYS_OF_WEEK: False
          SHOW_LANGUAGE: False
          SHOW_OS: False
          SHOW_PROJECTS: False
          SHOW_TIMEZONE: False
          SHOW_EDITORS: False
          SHOW_LANGUAGE_PER_REPO: False
          SHOW_SHORT_INFO: False
          IGNORED_REPOS: "mrasadatik"
          SHOW_LOC_CHART: False
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      # Step 1: Update Commit Stats by Time Period
      - name: Update the Commit Stats by Time Period
        uses: anmol098/waka-readme-stats@master
        with:
          SECTION_NAME: commit-time-distribution
          COMMIT_MESSAGE: "doc(cttp-stats): Update Commit Stats by Time Period section in README"
          SHOW_UPDATED_DATE: False
          SHOW_LINES_OF_CODE: False
          SHOW_TOTAL_CODE_TIME: False
          SHOW_PROFILE_VIEWS: False
          SHOW_COMMIT: True
          SHOW_DAYS_OF_WEEK: False
          SHOW_LANGUAGE: False
          SHOW_OS: False
          SHOW_PROJECTS: False
          SHOW_TIMEZONE: False
          SHOW_EDITORS: False
          SHOW_LANGUAGE_PER_REPO: False
          SHOW_SHORT_INFO: False
          IGNORED_REPOS: "mrasadatik"
          SHOW_LOC_CHART: False
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      # Step 1: Update Commit Stats by Week Days
      - name: Update the Commit Stats by Week Days
        uses: anmol098/waka-readme-stats@master
        with:
          SECTION_NAME: weekly-commit-stats
          COMMIT_MESSAGE: "doc(ctwd-stats): Update Commit Stats by Week Days section in README"
          SHOW_UPDATED_DATE: False
          SHOW_LINES_OF_CODE: False
          SHOW_TOTAL_CODE_TIME: False
          SHOW_PROFILE_VIEWS: False
          SHOW_COMMIT: False
          SHOW_DAYS_OF_WEEK: True
          SHOW_LANGUAGE: False
          SHOW_OS: False
          SHOW_PROJECTS: False
          SHOW_TIMEZONE: False
          SHOW_EDITORS: False
          SHOW_LANGUAGE_PER_REPO: False
          SHOW_SHORT_INFO: False
          IGNORED_REPOS: "mrasadatik"
          SHOW_LOC_CHART: False
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      # Step 1: Update Language Usages Stats
      - name: Update the Language Usages Stats
        uses: anmol098/waka-readme-stats@master
        with:
          SECTION_NAME: language-usage
          COMMIT_MESSAGE: "doc(lu-stats): Update Language Usages section in README"
          SHOW_UPDATED_DATE: False
          SHOW_LINES_OF_CODE: False
          SHOW_TOTAL_CODE_TIME: False
          SHOW_PROFILE_VIEWS: False
          SHOW_COMMIT: False
          SHOW_DAYS_OF_WEEK: False
          SHOW_LANGUAGE: True
          SHOW_OS: False
          SHOW_PROJECTS: False
          SHOW_TIMEZONE: False
          SHOW_EDITORS: False
          SHOW_LANGUAGE_PER_REPO: False
          SHOW_SHORT_INFO: False
          IGNORED_REPOS: "mrasadatik"
          SHOW_LOC_CHART: False
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      # Step 1: Update Operating System Stats
      - name: Update the Operating System Stats
        uses: anmol098/waka-readme-stats@master
        with:
          SECTION_NAME: operating-systems
          COMMIT_MESSAGE: "doc(os-stats): Update Operating System section in README"
          SHOW_UPDATED_DATE: False
          SHOW_LINES_OF_CODE: False
          SHOW_TOTAL_CODE_TIME: False
          SHOW_PROFILE_VIEWS: False
          SHOW_COMMIT: False
          SHOW_DAYS_OF_WEEK: False
          SHOW_LANGUAGE: False
          SHOW_OS: True
          SHOW_PROJECTS: False
          SHOW_TIMEZONE: False
          SHOW_EDITORS: False
          SHOW_LANGUAGE_PER_REPO: False
          SHOW_SHORT_INFO: False
          IGNORED_REPOS: "mrasadatik"
          SHOW_LOC_CHART: False
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      # Step 1: Update Projects Stats
      - name: Update the Projects Stats
        uses: anmol098/waka-readme-stats@master
        with:
          SECTION_NAME: project-stats
          COMMIT_MESSAGE: "doc(projects-stats): Update Projects section in README"
          SHOW_UPDATED_DATE: False
          SHOW_LINES_OF_CODE: False
          SHOW_TOTAL_CODE_TIME: False
          SHOW_PROFILE_VIEWS: False
          SHOW_COMMIT: False
          SHOW_DAYS_OF_WEEK: False
          SHOW_LANGUAGE: False
          SHOW_OS: False
          SHOW_PROJECTS: True
          SHOW_TIMEZONE: False
          SHOW_EDITORS: False
          SHOW_LANGUAGE_PER_REPO: False
          SHOW_SHORT_INFO: False
          IGNORED_REPOS: "mrasadatik"
          SHOW_LOC_CHART: False
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      # Step 1: Update Timezone Stats
      - name: Update the Timezone Stats
        uses: anmol098/waka-readme-stats@master
        with:
          SECTION_NAME: timezone-distribution
          COMMIT_MESSAGE: "doc(timezone-stats): Update Timezone section in README"
          SHOW_UPDATED_DATE: False
          SHOW_LINES_OF_CODE: False
          SHOW_TOTAL_CODE_TIME: False
          SHOW_PROFILE_VIEWS: False
          SHOW_COMMIT: False
          SHOW_DAYS_OF_WEEK: False
          SHOW_LANGUAGE: False
          SHOW_OS: False
          SHOW_PROJECTS: False
          SHOW_TIMEZONE: True
          SHOW_EDITORS: False
          SHOW_LANGUAGE_PER_REPO: False
          SHOW_SHORT_INFO: False
          IGNORED_REPOS: "mrasadatik"
          SHOW_LOC_CHART: False
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      # Step 1: Update Editors Stats
      - name: Update the Editors Stats
        uses: anmol098/waka-readme-stats@master
        with:
          SECTION_NAME: editor-usage
          COMMIT_MESSAGE: "doc(editors-stats): Update Editors section in README"
          SHOW_UPDATED_DATE: False
          SHOW_LINES_OF_CODE: False
          SHOW_TOTAL_CODE_TIME: False
          SHOW_PROFILE_VIEWS: False
          SHOW_COMMIT: False
          SHOW_DAYS_OF_WEEK: False
          SHOW_LANGUAGE: False
          SHOW_OS: False
          SHOW_PROJECTS: False
          SHOW_TIMEZONE: False
          SHOW_EDITORS: True
          SHOW_LANGUAGE_PER_REPO: False
          SHOW_SHORT_INFO: False
          IGNORED_REPOS: "mrasadatik"
          SHOW_LOC_CHART: False
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      # Step 1: Update Language Per Repo Stats
      - name: Update the Language Per Repo Stats
        uses: anmol098/waka-readme-stats@master
        with:
          SECTION_NAME: repository-languages
          COMMIT_MESSAGE: "doc(lpr-stats): Update Language Per Repo section in README"
          SHOW_UPDATED_DATE: False
          SHOW_LINES_OF_CODE: False
          SHOW_TOTAL_CODE_TIME: False
          SHOW_PROFILE_VIEWS: False
          SHOW_COMMIT: False
          SHOW_DAYS_OF_WEEK: False
          SHOW_LANGUAGE: False
          SHOW_OS: False
          SHOW_PROJECTS: False
          SHOW_TIMEZONE: False
          SHOW_EDITORS: False
          SHOW_LANGUAGE_PER_REPO: True
          SHOW_SHORT_INFO: False
          IGNORED_REPOS: "mrasadatik"
          SHOW_LOC_CHART: False
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      # Step 1: Update Short Info Stats
      - name: Update the Short Info Stats
        uses: anmol098/waka-readme-stats@master
        with:
          SECTION_NAME: profile-info
          COMMIT_MESSAGE: "doc(si-stats): Update Short Info section in README"
          SHOW_UPDATED_DATE: False
          SHOW_LINES_OF_CODE: False
          SHOW_TOTAL_CODE_TIME: False
          SHOW_PROFILE_VIEWS: False
          SHOW_COMMIT: False
          SHOW_DAYS_OF_WEEK: False
          SHOW_LANGUAGE: False
          SHOW_OS: False
          SHOW_PROJECTS: False
          SHOW_TIMEZONE: False
          SHOW_EDITORS: False
          SHOW_LANGUAGE_PER_REPO: False
          SHOW_SHORT_INFO: True
          IGNORED_REPOS: "mrasadatik"
          SHOW_LOC_CHART: False
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      # Step 1: Update LOC Chart Stats
      - name: Update the LOC Chart Stats
        uses: anmol098/waka-readme-stats@master
        with:
          SECTION_NAME: line-of-code-chart
          COMMIT_MESSAGE: "doc(loc-stats): Update LOC Chart section in README"
          SHOW_UPDATED_DATE: False
          SHOW_LINES_OF_CODE: False
          SHOW_TOTAL_CODE_TIME: False
          SHOW_PROFILE_VIEWS: False
          SHOW_COMMIT: False
          SHOW_DAYS_OF_WEEK: False
          SHOW_LANGUAGE: False
          SHOW_OS: False
          SHOW_PROJECTS: False
          SHOW_TIMEZONE: False
          SHOW_EDITORS: False
          SHOW_LANGUAGE_PER_REPO: False
          SHOW_SHORT_INFO: False
          IGNORED_REPOS: "mrasadatik"
          SHOW_LOC_CHART: True
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
